name: Deploy Infrastructure

on:
  # NOTE: Uncomment "push" block after creating an instance of this template
  # It is commented out to prevent CI/CD pipeline executions each time 
  # the template is updated.

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:                      
  deploy-sandbox:
    { % for env in values.environments % }
      { % if env === 'sandbox' % }
      if: true
      { % endif % }
    { % endfor % }
    with:
      app_pattern_name: "aws-ec2"
  deploy-dev:
    with:
      app_pattern_name: "aws-ec2"
  deploy-stage:
    with:
      app_pattern_name: "aws-ec2"
  deploy-prod:
    with:
      app_pattern_name: "aws-ec2"
